---
services:
  my_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-image:latest
    logging:
      driver: none
    container_name: my-application
    ports:
      - '80:8080'
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - './data:/app/data'
